Ecommerce01/Ecommerce01/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Ecommerce01.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [MaxLength(256, ErrorMessage = "Questo campo {0} deve essere lungo {1} caratteri!")]
        [Display(Name = "E-Mail")]
        [Index("User_UserName_Index", IsUnique = true)]
        [DataType(DataType.EmailAddress)]
        public string UserName { get; set; }


        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [MaxLength(50, ErrorMessage = "Questo campo {0} deve essere lungo {1} caratteri!")]
        [Display(Name = "Nome")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [MaxLength(50, ErrorMessage = "Questo campo {0} deve essere lungo {1} caratteri!")]
        [Display(Name = "Cognome")]
        public string LastName { get; set; }

       
        [Display(Name = "Data di Nascita")]
        //[Range(typeof(DateTime), "01/01/1910", "01/12/2050")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? DateBirth { get; set; }


        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [StringLength(20, MinimumLength = 10)]
        [Display(Name = "Telefono")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [MaxLength(100, ErrorMessage = "Questo campo {0} deve essere lungo {1} caratteri!")]
        [Display(Name = "Indirizzo")]
        public string Address { get; set; }

        [DataType(DataType.ImageUrl)]
        public string Photo { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [Range(1, double.MaxValue, ErrorMessage = "Devi selezionare un {0}")]
        [Display(Name = "Regione")]
        public int DepartamentId { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [Range(1, double.MaxValue, ErrorMessage = "Devi selezionare un {0}")]
        [Display(Name = "Provincia")]
        public int ProvinceId { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [Range(1, double.MaxValue, ErrorMessage = "Devi selezionare un {0}")]
        [Display(Name = "Comune")]
        public int CityId { get; set; }

        [Required(ErrorMessage = "Questo campo {0} è necessario!")]
        [Range(1, double.MaxValue, ErrorMessage = "Devi selezionare un {0}")]
        [Display(Name = "Azienda")]
        public int CompanyId { get; set; }

        [Display(Name = "Utente")]
        public string FullName { get {return string.Format("{0} {1}", FirstName, LastName); } }

        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        public virtual Departament Departament { get; set; }

        public virtual Province Province { get; set; }

        public virtual City City { get; set; }

        public virtual Company Company { get; set; }

        public virtual ICollection<Category> Categories { get; set; }
    }
}

Ecommerce01/Ecommerce01/Controllers/GenericoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce01.Models;

namespace Ecommerce01.Controllers
{
    public class GenericoController : Controller
    {
        private readonly Ecommerce01Context _db = new Ecommerce01Context();
        //////add
        ////[HttpGet]
        public JsonResult GetProvinces(int departamentId)
        {
            //can be
            //https://stackoverflow.com/questions/4596371/what-are-the-downsides-to-turning-off-proxycreationenabled-for-ctp5-of-ef-code-f
            //http://www.c-sharpcorner.com/UploadFile/db2972/json-result-in-controller-sample-in-mvc-day-13/
            _db.Configuration.ProxyCreationEnabled = false;
            var provinces = _db.Provinces.Where(p => p.DepartamentId == departamentId);
            // can be  return Json(modelList,JsonRequestBehavior.AllowGet);
            return Json(provinces);
        }

        public JsonResult GetCities(int provinceId)
        {
            //can be
            //https://stackoverflow.com/questions/4596371/what-are-the-downsides-to-turning-off-proxycreationenabled-for-ctp5-of-ef-code-f
            //http://www.c-sharpcorner.com/UploadFile/db2972/json-result-in-controller-sample-in-mvc-day-13/
            _db.Configuration.ProxyCreationEnabled = false;
            var cities = _db.Cities.Where(c => c.ProvinceId == provinceId);
            // can be  return Json(modelList,JsonRequestBehavior.AllowGet);
            return Json(cities);
        }


        public JsonResult GetCompanies(int cityId)
        {
            //can be
            //https://stackoverflow.com/questions/4596371/what-are-the-downsides-to-turning-off-proxycreationenabled-for-ctp5-of-ef-code-f
            //http://www.c-sharpcorner.com/UploadFile/db2972/json-result-in-controller-sample-in-mvc-day-13/
            _db.Configuration.ProxyCreationEnabled = false;
            var companies = _db.Companies.Where(c => c.CityId == cityId);
            // can be  return Json(modelList,JsonRequestBehavior.AllowGet);
            return Json(companies);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ecommerce01/Ecommerce01/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ecommerce01.Classes;
using Ecommerce01.Models;
using PagedList;
using PagedList.Mvc;

namespace Ecommerce01.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private Ecommerce01Context db = new Ecommerce01Context();
              
        private const int itemsonPage = 3;
        // GET: Users
        public ActionResult Index(int? page = null)
        {
            page = (page ?? 1);
            var users = db.Users
                .Include(u => u.City)
                .Include(u => u.Company)
                .Include(u => u.Departament)
                .Include(u => u.Province)
                .OrderBy(u => u.UserName);
            return View(users.ToPagedList((int)page, itemsonPage));
           
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
             var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(DropDownHelper.GetCities(), "CityId", "Name");
            ViewBag.CompanyId = new SelectList(DropDownHelper.GetCompanies(), "CompanyId", "Name");
            ViewBag.DepartamentId = new SelectList(DropDownHelper.GetDepartaments(), "DepartamentId", "Name");
            ViewBag.ProvinceId = new SelectList(DropDownHelper.GetProvinces(), "ProvinceId", "Name");
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,UserName,FirstName,LastName,DateBirth,Phone,Address,Photo,PhotoFile,DepartamentId,ProvinceId,CityId,CompanyId")] User user, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //?dupplicati
               if (db.Users.Any(u => u.UserName.Equals(user.UserName) && u.CompanyId.Equals(user.CompanyId)))
               {
                    ModelState.AddModelError(string.Empty, "Esiste già un Registro con lo stesso valore");
                }
                else
                {
                    db.Users.Add(user);
                    try
                    {
                        db.SaveChanges();
                        //attention Role User
                        UsersHelper.CreateUserAsp(user.UserName, "User");

                        if (user.PhotoFile != null)
                        {
                            var folder = "~/Content/Users";
                            //can be extention png,jpeg,gif,jpg
                            var file = string.Format("{0}.jpg", user.UserId);
                            //var response = FilesHelper.UploadPhoto(user.PhotoFile, folder, file);
                            var response = FilesHelper.UploadPhoto(PhotoFile, folder, file, user.Photo);
                            if (response)
                                if (response)
                            {
                                var pic = string.Format("{0}/{1}", folder, file);
                                user.Photo = pic;
                                db.Entry(user).State = EntityState.Modified;
                                db.SaveChanges();
                            }
                        }
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        //ModelState.AddModelError(string.Empty, ex.Message);
                        ModelState.AddModelError(string.Empty, ex.Message + " NON RIESCO A SALVARE - User Duplicato");
                    }
                }
            }

            ViewBag.CityId = new SelectList(DropDownHelper.GetCities(), "CityId","Name", user.CityId);
            ViewBag.CompanyId = new SelectList(DropDownHelper.GetCompanies(), "CompanyId", "Name", user.CompanyId);
            ViewBag.DepartamentId = new SelectList(DropDownHelper.GetDepartaments(), "DepartamentId", "Name", user.DepartamentId);
            ViewBag.ProvinceId = new SelectList(DropDownHelper.GetProvinces(), "ProvinceId", "Name", user.ProvinceId);
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.CityId = new SelectList(DropDownHelper.GetCities(), "CityId", "Name", user.CityId);
            ViewBag.CompanyId = new SelectList(DropDownHelper.GetCompanies(), "CompanyId", "Name", user.CompanyId);
            ViewBag.DepartamentId = new SelectList(DropDownHelper.GetDepartaments(), "DepartamentId", "Name", user.DepartamentId);
            ViewBag.ProvinceId = new SelectList(DropDownHelper.GetProvinces(), "ProvinceId", "Name", user.ProvinceId);

            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,UserName,FirstName,LastName,DateBirth,Phone,Address,Photo,PhotoFile,DepartamentId,ProvinceId,CityId,CompanyId")] User user, HttpPostedFileBase PhotoFile)
        {
            if (ModelState.IsValid)
            {
                //var folder = "~/Content/Users";
                //var file = $"{user.UserId}.jpg";
                if (user.PhotoFile != null)
                {
                    var file = string.Format("{0}.jpg", user.UserId);
                    var folder = "~/Content/Users";
                    //var response = FilesHelper.UploadPhoto(user.PhotoFile, folder, file);
                    var response = FilesHelper.UploadPhoto(PhotoFile, folder, file, user.Photo);
                    user.Photo = string.Format("{0}/{1}", folder, file);
                }
                //if user change e-amail
                using (var db2 = new Ecommerce01Context())
                {
                    var currentUser = db2.Users.Find(user.UserId);

                    if (currentUser.UserName != user.UserName)
                    {
                        UsersHelper.UpdateUserName(currentUser.UserName, user.UserName);
                    }
                }

                db.Entry(user).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message + " NON RIESCO A SALVARE, email duplicata presente nel sistema");
                    //return View(user);
                    //ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            ViewBag.CityId = new SelectList(DropDownHelper.GetCities(), "CityId", "Name", user.CityId);
            ViewBag.CompanyId = new SelectList(DropDownHelper.GetCompanies(), "CompanyId", "Name", user.CompanyId);
            ViewBag.DepartamentId = new SelectList(DropDownHelper.GetDepartaments(), "DepartamentId", "Name", user.DepartamentId);
            ViewBag.ProvinceId = new SelectList(DropDownHelper.GetProvinces(), "ProvinceId", "Name", user.ProvinceId);
            return View(user);
        }
                 


        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            //last add
            UsersHelper.DeleteUser(user.UserName, "User");
            return RedirectToAction("Index");
        }



    protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ecommerce01/Ecommerce01/Views/Users/Create.cshtml
@model Ecommerce01.Models.User

@{
    ViewBag.Title = "Crea";
}

<h2>Crea</h2>

@using (Html.BeginForm("Create", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.DateBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "form-control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.PhotoFile, null, new { type = "file", @class = "input-file" })
                    @*<input type="submit" value="questo valore" />*@
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProvinceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
       
     </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Ritorna", "Index", new { }, new { @class = "btn-outline-primary" })
            <input type="submit" value="Crea" class="btn btn-info" />
        </div>
    </div>
   }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/script.js")
    @* per attivare solo le provincie da una determinanata regione/ le citta di determinata Provincia *@
    <script type="text/javascript">
        var Url = '@Url.Action("GetProvinces", "Generico")';
        var Url2 = '@Url.Action("GetCities", "Generico")';
        var Url3 = '@Url.Action("GetCompanies", "Generico")';
    </script>
}

Ecommerce01/Ecommerce01/Views/Users/Delete.cshtml
@model Ecommerce01.Models.User

@{
    ViewBag.Title = "Elimina";
}

<h2>Elimina</h2>

<h3>E' sicuro di volere eliminare questo Registro ?</h3>
<div>
    <h4>Utente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Departament.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Departament.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Province.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Province.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Ritorna", "Index", new { }, new { @class = "btn-outline-primary" })
            <input type="submit" value="Elimina" class="btn btn-danger" />
        </div>
    }
</div>

Ecommerce01/Ecommerce01/Views/Users/Edit.cshtml
@model Ecommerce01.Models.User

@{
    ViewBag.Title = "Modifica";
}

<h2>Modifica</h2>

@using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.Photo)
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.DateBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.DateBirth)
                @Html.EditorFor(model => model.DateBirth, new { htmlAttributes = new { @class = "datepicker form-control" } })
                
                @* @Html.TextBoxFor(model => model.DateBirth, "{0:dd/MM/yyyy}", htmlAttributes: new { @type = "date", @class = "form-control" } )*@
                @*@Html.TextBoxFor(model => model.DateBirth)*@
                @*@Html.TextBoxFor(model => model.DateBirth, String.Format("{0:dd/MM/yyyy}"))*@
                @*@Html.EditorFor(model => model.DateBirth, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.DateBirth, "", new { @class = "text-danger" })*@
            
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.DepartamentId, "DepartamentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartamentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartamentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProvinceId, "ProvinceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProvinceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProvinceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "CityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @if (!string.IsNullOrEmpty(Model.Photo))
                    {
                        <img src="@Url.Content(Model.Photo)" alt="Image" style="width: 150px; height: 150px; max-width: 100%; height: auto;" />
                    }
                    @Html.TextBoxFor(model => model.PhotoFile, null, new { type = "file", @class = "input-file" })

                </span>
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Ritorna", "Index", new { }, new { @class = "btn-outline-primary" })
                <input type="submit" value="Salva" class="btn btn-info" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/script.js")
    @* per attivare solo le provincie da una determinanata regione/ le citta di determinata Provincia *@
    <script type="text/javascript">
        var Url = '@Url.Action("GetProvinces", "Generico")';
        var Url2 = '@Url.Action("GetCities", "Generico")';
        var Url3 = '@Url.Action("GetCompanies", "Generico")';
    </script>
}